ARG  CODE_VERSION=latest
FROM opensuse/leap:${CODE_VERSION}

RUN zypper --non-interactive install cmake gcc gcc-c++ gcc-fortran make patch sed \
    libX11-devel libXft-devel libXpm-devel libXext-devel \
    libXmu-devel Mesa-libGL-devel freeglut-devel ncurses-devel \
    curl libcurl-devel bzip2 libbz2-devel gzip unzip tar \
    libexpat-devel subversion git flex bison makedepend lsb-release python-devel \
    libxml2-devel libopenssl-devel krb5-devel wget \
    libcurl-devel automake autoconf libtool which

RUN git clone https://github.com/FairRootGroup/fairsoft_config.git && git clone --single-branch --branch RC_Jun19 https://github.com/FairRootGroup/FairSoft.git
RUN cd FairSoft && ./configure.sh   ../fairsoft_config/config/fairsoft_build_release_linux && cd .. && rm -rf FairSoft
ENV SIMPATH=/fairsoft_build_release
ENV PATH=$SIMPATH/bin:$PATH
RUN git clone --single-branch --branch dev https://github.com/FairRootGroup/FairRoot.git && cd FairRoot && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/FairRoot_install
RUN cd FairRoot/build && make -j4 install && cd .. && rm -rf build
