ARG  CODE_VERSION=latest
FROM centos:${CODE_VERSION}

RUN yum install -y cmake gcc gcc-c++ gcc-gfortran make patch sed \
    libX11-devel libXft-devel libXpm-devel libXext-devel \
    libXmu-devel mesa-libGLU-devel mesa-libGL-devel ncurses-devel \
    curl curl-devel bzip2 bzip2-devel gzip unzip tar \
    expat-devel subversion git flex bison imake redhat-lsb-core python-devel \
    libxml2-devel wget openssl-devel krb5-devel \
    automake autoconf libtool which && yum clean all
RUN git clone https://github.com/FairRootGroup/fairsoft_config.git && git clone --single-branch --branch RC_Jun19 https://github.com/FairRootGroup/FairSoft.git
RUN cd FairSoft && ./configure.sh   ../fairsoft_config/config/fairsoft_build_release_linux && cd .. && rm -rf FairSoft
ENV SIMPATH=/fairsoft_build_release
ENV PATH=$SIMPATH/bin:$PATH
RUN git clone --single-branch --branch dev https://github.com/FairRootGroup/FairRoot.git && cd FairRoot && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/FairRoot_install
RUN cd FairRoot/build && make -j4 install && cd .. && rm -rf build
