ARG  CODE_VERSION=latest
FROM ubuntu:${CODE_VERSION}

RUN apt-get update -y

RUN apt-get -y install  cmake cmake-data g++ gcc gfortran \
  debianutils build-essential make patch sed \
  libx11-dev libxft-dev libxext-dev libxpm-dev libxmu-dev \
  libglu1-mesa-dev libgl1-mesa-dev \
  libncurses5-dev curl libcurl4-openssl-dev bzip2 libbz2-dev gzip unzip tar \
  subversion git xutils-dev flex bison lsb-release python-dev \
  libc6-dev-i386 libxml2-dev wget libssl-dev libkrb5-dev \
  automake autoconf libtool

RUN git clone https://github.com/FairRootGroup/fairsoft_config.git && git clone --single-branch --branch RC_Jun19 https://github.com/FairRootGroup/FairSoft.git
RUN cd FairSoft && ./configure.sh   ../fairsoft_config/config/fairsoft_build_release_linux && cd .. && rm -rf FairSoft
ENV SIMPATH=/fairsoft_build_release
ENV PATH=$SIMPATH/bin:$PATH
RUN git clone --single-branch --branch dev https://github.com/FairRootGroup/FairRoot.git && cd FairRoot && mkdir build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX=/FairRoot_install
RUN cd FairRoot/build && make -j4 install && cd .. && rm -rf build
